# This is a basic workflow to help you get started with Actions

name: app

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
      deploy:
        name: Build, Deploy to S3 bucket
        runs-on: [ubuntu-latest]
    
        strategy:
          matrix:
            node-version: [18.x]
    
        steps:
          - uses: actions/checkout@v2
    
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
    
          - name: Install yarn
            run: npm install --location=global yarn
    
          - name: Package install
            run: yarn
            
          - name: Build
            run: CI=false yarn build
    
          - name: Transfer to S3 for serving static
            uses: jakejarvis/s3-sync-action@master
            with:
              args: --acl public-read --follow-symlinks --delete
            env:
              AWS_S3_BUCKET: app-classic.terraswap.io
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
              AWS_REGION: ap-northeast-2
              SOURCE_DIR: 'build'
              
          - name: Invalidate Cloudfront Distribution
            uses: awact/cloudfront-action@master
            env:
              SOURCE_PATH: '/*'
              AWS_REGION: ap-northeast-2
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
              DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID_APP_CLASSIC }}
